#ifndef CONSTANTS_H
#define CONSTANTS_H

#define REPEAT(x) for (int i = 0; i < x; ++i)

#define WINDOW_HEIGHT 800
#define WINDOW_WIDTH 1400

#define GRAV_ACCELERATION 980.0f

#define PLAYER_SIZE 80
#define PLAYER_BASE_JUMP_VELOCITY -500.0f

#define FLOOR_HEIGHT 50
#define FLOOR_OFFSET FLOOR_HEIGHT
#define PLAYER_OFFSET (FLOOR_OFFSET + PLAYER_SIZE)

#define FPS_LIMIT 120

#define EVENT /*ENGINE EVENT FUNCTION*/
#define ENTITY_METHOD /*ENGINE ENTITY FUNCTION*/
#define MOVABLE_ENTITY_METHOD /*ENGINE MOVABLE ENTITY FUNCTION*/

#endif // CONSTANTS_H
