#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_HEIGHT 800
#define WINDOW_WIDTH 1200

#define GRAV_ACCELERATION 980.0f

#define PLAYER_SIZE 80
#define PLAYER_BASE_JUMP_VELOCITY -500.0f

#define FLOOR_HEIGHT 50
#define FLOOR_OFFSET FLOOR_HEIGHT
#define PLAYER_OFFSET (FLOOR_OFFSET + PLAYER_SIZE)

#define FPS_LIMIT 120

#endif // CONSTANTS_H
